apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: partition
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/partition/ }
      backendRefs:
        - name: partition
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: entitlements
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/entitlements/ }
      backendRefs:
        - name: entitlements
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: legal
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/legal/ }
      backendRefs:
        - name: legal
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: schema
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/schema-service/ }
      backendRefs:
        - name: schema
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: storage
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/storage/ }
      backendRefs:
        - name: storage
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: search
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/search/ }
      backendRefs:
        - name: search
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: indexer
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/indexer/ }
      backendRefs:
        - name: indexer
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: indexer-queue
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/indexer-queue/ }
      backendRefs:
        - name: indexer-queue
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: file
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/file/ }
      backendRefs:
        - name: file
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: workflow
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/workflow/ }
      backendRefs:
        - name: workflow
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unit
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/unit/ }
      backendRefs:
        - name: unit
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: crs-catalog
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/crs/catalog/ }
      backendRefs:
        - name: crs-catalog
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: crs-conversion
  namespace: osdu
spec:
  parentRefs:
    - name: spi-gateway
      namespace: aks-istio-ingress
  hostnames:
    - "${INGRESS_HOST_OSDU}"
  rules:
    - matches:
        - path: { type: PathPrefix, value: /api/crs/converter/ }
      backendRefs:
        - name: crs-conversion
          port: 80
