apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: entitlements
  namespace: flux-system
spec:
  targetNamespace: osdu
  dependsOn:
    - name: partition
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./software/charts/osdu-spi-service
      sourceRef:
        kind: GitRepository
        name: osdu-spi-stack-system
  values:
    image:
      repository: ${ENTITLEMENTS_IMAGE_REPOSITORY}
      tag: "${ENTITLEMENTS_IMAGE_TAG}"
    redisTls: true
    nodeSelector:
      agentpool: osdu
    tolerations:
      - key: workload
        operator: Equal
        value: "osdu"
        effect: NoSchedule
    env:
      - name: SPRING_APPLICATION_NAME
        value: entitlements
      - name: SERVER_SERVLET_CONTEXTPATH
        value: /api/entitlements/v2/
      - name: ACCEPT_HTTP
        value: "true"
      - name: AZURE_ISTIOAUTH_ENABLED
        value: "true"
      - name: AZURE_PAAS_WORKLOADIDENTITY_ISENABLED
        value: "true"
      - name: AZURE_MSI_ISENABLED
        value: "true"
      - name: SPRING_CONFIG_NAME
        value: common,application
      - name: SERVICE_DOMAIN_NAME
        value: dataservices.energy
      - name: ROOT_DATA_GROUP_QUOTA
        value: "5000"
      - name: REDIS_TTL_SECONDS
        value: "1"
      - name: REDIS_DATABASE
        value: "2"
      - name: PARTITION_SERVICE_ENDPOINT
        value: http://partition/api/partition/v1
