apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: schema
  namespace: osdu-flux
spec:
  targetNamespace: osdu
  dependsOn:
    - name: entitlements
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./software/charts/osdu-spi-service
      sourceRef:
        kind: GitRepository
        name: osdu-spi-stack-system
  values:
    image:
      repository: ${SCHEMA_IMAGE_REPOSITORY}
      tag: "${SCHEMA_IMAGE_TAG}"
      digest: "${SCHEMA_IMAGE_DIGEST}"
    redisTls: true
    nodeSelector:
      agentpool: osdu
    tolerations:
      - key: workload
        operator: Equal
        value: "osdu"
        effect: NoSchedule
    env:
      - name: SPRING_APPLICATION_NAME
        value: schema
      - name: SERVER_SERVLET_CONTEXTPATH
        value: /api/schema-service/v1/
      - name: SERVER_PORT
        value: "8080"
      - name: ACCEPT_HTTP
        value: "true"
      - name: AZURE_ISTIOAUTH_ENABLED
        value: "true"
      - name: AZURE_PAAS_WORKLOADIDENTITY_ISENABLED
        value: "true"
      - name: AZURE_MSI_ISENABLED
        value: "true"
      - name: COSMOSDB_DATABASE
        value: osdu-db
      - name: AZURE_SYSTEM_STORAGECONTAINERNAME
        value: system
      - name: SERVICEBUS_TOPIC_NAME
        value: schemachangedtopic
      - name: EVENT_GRID_ENABLED
        value: "false"
      - name: EVENT_GRID_TOPIC
        value: schemachangedtopic
      - name: SERVICE_BUS_ENABLED
        value: "true"
      - name: PARTITION_SERVICE_ENDPOINT
        value: http://partition/api/partition/v1
      - name: ENTITLEMENTS_SERVICE_ENDPOINT
        value: http://entitlements/api/entitlements/v2
      - name: ENTITLEMENTS_SERVICE_API_KEY
        value: OBSOLETE
