apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: storage
  namespace: osdu-flux
spec:
  targetNamespace: osdu
  dependsOn:
    - name: legal
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./software/charts/osdu-spi-service
      sourceRef:
        kind: GitRepository
        name: osdu-spi-stack-system
  values:
    image:
      repository: ${STORAGE_IMAGE_REPOSITORY}
      tag: "${STORAGE_IMAGE_TAG}"
      digest: "${STORAGE_IMAGE_DIGEST}"
    redisTls: true
    nodeSelector:
      agentpool: osdu
    tolerations:
      - key: workload
        operator: Equal
        value: "osdu"
        effect: NoSchedule
    istioProxyPin:
      enabled: true
    env:
      - name: SPRING_APPLICATION_NAME
        value: storage
      - name: SERVER_SERVLET_CONTEXTPATH
        value: /api/storage/v2/
      - name: ACCEPT_HTTP
        value: "true"
      - name: AZURE_ISTIOAUTH_ENABLED
        value: "true"
      - name: AZURE_PAAS_WORKLOADIDENTITY_ISENABLED
        value: "true"
      - name: AZURE_MSI_ISENABLED
        value: "true"
      - name: COSMOSDB_DATABASE
        value: osdu-db
      - name: AZURE_SERVICEBUS_ENABLED
        value: "true"
      - name: AZURE_EVENTGRID_ENABLED
        value: "false"
      - name: SERVICEBUS_TOPIC_NAME
        value: recordstopic
      - name: SERVICEBUS_V2_TOPIC_NAME
        value: recordstopic-v2
      - name: REDIS_DATABASE
        value: "4"
      - name: PARTITION_SERVICE_ENDPOINT
        value: http://partition/api/partition/v1
      - name: ENTITLEMENTS_SERVICE_ENDPOINT
        value: http://entitlements/api/entitlements/v2
      - name: ENTITLEMENTS_SERVICE_API_KEY
        value: OBSOLETE
      - name: LEGAL_SERVICE_ENDPOINT
        value: http://legal/api/legal/v1
      - name: LEGAL_SERVICE_REGION
        value: southcentralus
      - name: LEGAL_SERVICEBUS_TOPIC_NAME
        value: legaltagschangedtopiceg
      - name: LEGAL_SERVICEBUS_TOPIC_SUBSCRIPTION
        value: eg_sb_legaltagchangedsubscription
      - name: CRS_CONVERSION_SERVICE_ENDPOINT
        value: http://crs-conversion/api/crs/converter/v2
      - name: POLICY_SERVICE_ENDPOINT
        value: http://policy/api/policy/v1
      - name: OPA_ENABLED
        value: "false"
