apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: platform
  labels:
    app.kubernetes.io/managed-by: osdu-spi-stack
spec:
  version: 8.18.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: platform
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      tolerations:
        - effect: NoSchedule
          key: workload
          value: "platform"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - platform
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
