apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: osdu-spi-init
  namespace: flux-system
spec:
  targetNamespace: osdu
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./software/charts/osdu-spi-init
      sourceRef:
        kind: GitRepository
        name: osdu-spi-stack-system-v3
  values:
    partitions:
      - opendes
